makefile, package.json
`npm install` runs `prepublish` npm/npm#3059
So we're going to publish with `make publish`
=> use make publish instead of npm publish

Gulpfile.js, lib/each.js, lib/implore.es6.js, src/APIActionCreator.es6.js, test/src/api-action-creator-tests.js
I did a slight refactor on the API / Implore (promises really). Updated / added comments. Cleaned up some conditional logic to reduce indentations. 
We were checking route with an invariant to see if it was a string, then passing it to check payload to validate it wasn't empty. I removed that check and added it to the invariant. 
Now to the bug with createRequest:
There was an issue with how the logic was setup as Jake and I discussed. The request parameter was not actually the request, but rather the first parameter passed to the action creator's method while submitting an action. To fix this problem got rid of `(request, ...args)` in favor of `(...args)` and also added validation to ensure that if we are passing arguments to an API action creator that the user implemented …
=> API Refactor & Fixed a bug in createRequest

src/ActionCreator.es6.js
We had some issues with our debug messages because we were not checking for the valid messages returned from React's library. 
There was two different types of strings that were returned when we find 'expected'. One is for primitives and the other is for more complex objects (like instanceOf, arrays, etc). We were missing the second check.
=> Fixed debug messages

src/Dispatcher.es6.js, src/ObjectOrientedStore.es6.js
Optimize all the things... except... there is one downside to this optimization. The deregister isn't that optimized because I don't iterate over all the registered actions to remove the store. The reason is because the complexity to do this is pretty high and we don't ever deregister stores.... so i left it how it is. Since you have to iterate over every action (n), then search the index for the store_id (n). So it's o(n^2).
=> Added optimizations to dispatching

Gulpfile.js, package.json, src/ImmutableStore.es6.js, src/ObjectOrientedStore.es6.js, src/Store.es6.js
Babel 5.0 has breaking changes that now impose restrictions defined in the ES6 specification. 
https://babeljs.io/blog/2015/03/31/5.0.0/#breaking-changes
I also upgrade dependencies & made our core dependencies a little more lax in which versions we use.
=> Refactored to work with ES6 restrictions

src/ImmutableStore.es6.js
This allows us to disable performance checks in production when the `CHECK_IMMUTABILITY` env variable is not set to `true`
=> Fixes #34 - disable immutable checks in production

package.json, src/ImmutableStore.es6.js
I reverted the ugly closure fix for babel back to how it was.
I also moved babel & babel core to be core dependencies since we use them when you require fluxthis's built file.
=> Upgraded babel and reverted fix. Moved babel to core dep

package.json, src/ConstantCollection.es6.js, test/src/constant-collection-tests.js
allow constant collections to be used in normal objects (because they have a toString method now)
=> constant collection tostrings

src/ConstantCollection.es6.js, src/Dispatcher.es6.js, test/src/constant-collection-tests.js, test/src/integration-tests.js
constant collections were breaking a stringify used to check for immutability in actions.  This is somewhat of a work-around, and doesnt address the larger issue, but should be OK for now.
=> Payload stringify

src/ActionCreator.es6.js, src/debug.es6.js, test/src/action-creator-tests.js
Moved from using normal objects in the debugger to using Maps to be compatible with Constant Collections & string sources/types for actions.
I moved validating that we already have an actionType registered with an actionSource to the action creator. It didn't belong in the debug file. 
Added a couple tests for constant collections.
=> Fixed debugging constant collections

package.json, src/FluxThis.es6.js, test/webpack.config.js, webpack.config.js
The babel polyfill should be defined once at the main entry point to an application, and a runtime error will occur if  it is required multiple times.
```
Uncaught Error: only one instance of babel/polyfill is allowed
```
This isn't suitable for third party libraries, which should be directly compiled to rely on babel-runtime.
This PR therefore removes the babel polyfill, and instead requires on the babel runtime compile option. From the babel runtime [docs](http://babeljs.io/docs/usage/runtime/)
```
[...] you can use built-ins such as Promise, Set, Symbol etc as well use as all the Babel features that require a polyfill seamlessly, without global pollution, making it extremely suitable for libraries.
```
Relevant issues - #29, #60
=> Remove babel polyfill

lib/implore.es6.js
xhr response Content-Type header may contain other values from the
server.  ex: "application/json; charset=utf-8"
=> regex contains test instead of equality

README.mdown, lib/each.es6.js, lib/implore.es6.js, lib/request.es6.js, src/APIActionCreator.es6.js, src/ActionCreator.es6.js, src/ImmutableStore.es6.js, src/ObjectOrientedStore.es6.js, src/StoreTestUtils.es6.js, src/debug.es6.js, test/server.js, test/src/api-action-creator-tests.js, test/src/integration-tests.js, test/src/request-tests.js, test/src/tests.js
* moved each.js to es6 compatible. 
* Removed promise from implore since it caused invariants / exceptions to be displayed in a horrible wrapped way.
* Return new request object that has an abort method to be handled by application. 
```
onClick() {
const request = this.state.request;
// If the previous request is still executing then cancel
if (request && !request.isDone()) {
request.abort();
}
request = actionCreator.doSomething();
this.setState({request});
}
```
=> Added ability to abort XHR requests from api action creator

lib/implore.es6.js, test/src/api-action-creator-tests.js
This PR builds upon the work of #113 / #114 by providing access to the original response body if a JSON error occurrs during parsing
=> [#115] No longer replace response body if error during json parse

lib/implore.es6.js, test/server.js, test/src/api-action-creator-tests.js
I ran a few small manual tests in addition to writing an automated test for this, and all seems to indicate that this works as expected. Feel free to give it a spin with more "real life" cases before merging the PR if you'd like; I haven't had a chance to actually do that yet, but will do it later on.
=> Fix for #142 (allows named parameters with file extensions)

package.json
`babel` and `babel-core` are dev dependencies as they're used in the build process.
Node Security Platform have put up an advisory regarding one of babels v5 dependencies - https://nodesecurity.io/advisories/118
As a dependency of `fluxthis`, applications which use the `nsp` module will receive false positive warnings that a module on their dependency tree has an issue. Moving these to dev dependencies should remove this warning.
__Update:__ Confirmed that `nsp` warnings no longer show when using this branch.
=> Move babel to dev dependency

src/Dispatcher.es6.js
The message before was:
```
Cannot dispatch in the middle of a dispatch in the middle of a dispatch
```
Which isn't too informative
It now says:
```es6
`Cannot dispatch in the middle of a dispatch in the middle of a dispatch. Was dispatching action ${JSON.stringify(pendingAction)} when this action was called: ${JSON.stringify(nextAction)}`
```
=> Log which actions dispatched during a dispatch

lib/implore.es6.js, test/src/api-action-creator-tests.js
Should not need to fallback to ActionCreators and custom XHR calls just to read a header that isn't `'Content-Type'`
=> Expose response headers to APIActionCreators

.gitignore, Gulpfile.js, example/index.html, example/src/action-creator.js, example/src/app.js, example/src/index.js, example/src/store.js, example/webpack.config.js, package.json, webpack.config.js
This PR moves the immutable library to a peer dependency to allow application developers to make use of their existing immutable version, rather than having to bundle two (or be dependent on the version bundled in fluxthis). This reduces the overall fluxthis build size by over a third (see below).
```
$ gulp build-prod
[12:27:02] Using gulpfile /fluxthis/gulpfile.js
[12:27:02] Starting 'build-prod'...
[12:27:05] Version: webpack 1.15.0
Asset     Size  Chunks             Chunk Names
FluxThis.min.js   156 kB       0  [emitted]  FluxThis
FluxThis.min.js.map  1.05 MB       0  [emitted]  FluxThis
[12:27:05] Finished 'build-prod' after 3.49 s
```
```
$ gulp build-prod
[12:26:28] Using gulpfile /fluxthis/gulpfile.js
[12:26:28] Starting 'build-prod'...
[12:26:30] Version: webpack 1.15.0
Asset …
```
=> Move immutable to peer dependency

src/Store.es6.js
When running with the latest react, a warning is shown in the console due to the use of `isMounted`
> isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
Although this check is probably not required with the listener being cleared on unmount, the common update is to store our own flag for whether the component is mounted or not. This flag uses the same `__flux` prefix as the change listener.
https://github.com/facebook/react/issues/3417#issuecomment-121649937
=> Remove call to deprecated isMounted check

src/StoreTestUtils.es6.js, test/src/object-oriented-store-tests.js
This PR adds support for setting private members during tests, in a similar implementation to the existing `mockPublicMethods` function.
This will allow developers to follow the common testing pattern of [Arrange, Act, Assert](http://wiki.c2.com/?ArrangeActAssert) when developing Store tests.
In particular, it will allow for stores to be in a well defined and known state before dispatching an action, and asserting on the new state.
Documentation added https://github.com/addthis/fluxthis.io/pull/15
=> Add support for setting private members during tests

src/Store.es6.js
This PR removes an invariant check which currently stops components with the same display name from acting as controller views for the same store.
I've been working around this particular check for a while, but as the application I work on grows in size and we try to reuse functionality, the more this invariant becomes a blocker. In our particular use case we started out with a small application with a single container at our top-level, but as our single-page application spread we found the need for page-specific containers. As functionality became shared across pages we then needed reusable connected components which is where this invariant reared it's head.
Example Scenario:
Sales reports that have various graphs upon them which are all data-driven from a store. The graphs functionality …
=> Allowing stores to have controller views that use the same display name.

lib/implore.es6.js
Fixes #149 
This PR resolves an existing issue where if there is a network error the failure handler was not getting called and the API call would remain in the `pending` state.
To resolve this issue, a further check has been added into `lib/implore.es6.js` on the `onreadystatechange` event handler. This check handles the scenario when `readystate` is 4 and `status` is 0 - this occurs when the network has failed.
Along with this, updates have been made to the `abort` functionality.
A `readystate` of 4 and `status` of 0 occurs when the user has manually aborted the xhr request as well. To avoid calling the callback twice, i.e. once during `abort` and once during `onreadystatechange`, I have overwritten the xhr `abort` method.
This method now calls the callback with the response of …
=> Call failure handler on network error

package.json
- Updates the qs package to `^6.5.1`
- Address security advisory (High severity): https://snyk.io/vuln/npm:qs:20170213
I'm using FluxThis on a project and Snyk raised the issue: https://snyk.io/test/npm/fluxthis?severity=high&severity=medium&severity=low
All tests continue to pass after updating this package. It's only used in one place and the API of the `qs` library hasn't changed for what Fluxthis uses it for.
=> Update qs package to address security advisory
